// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTRM8KwsehnuKLvPEAsLrwOqlthiD-idM',
    appId: '1:428089562800:web:5259e6521ab88b5bd94d75',
    messagingSenderId: '428089562800',
    projectId: 'wechat-app-47ec2',
    authDomain: 'wechat-app-47ec2.firebaseapp.com',
    storageBucket: 'wechat-app-47ec2.appspot.com',
    measurementId: 'G-NZKMJ5YG5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDffCY0XdBu7jy6dpVS1vE3-kuLZayAeOk',
    appId: '1:428089562800:android:08ab3ebc3500ee01d94d75',
    messagingSenderId: '428089562800',
    projectId: 'wechat-app-47ec2',
    storageBucket: 'wechat-app-47ec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZkW1aSGEdxt4ZZqWt1MS1NIg0ZlYZ6TM',
    appId: '1:428089562800:ios:f04afb752a55092bd94d75',
    messagingSenderId: '428089562800',
    projectId: 'wechat-app-47ec2',
    storageBucket: 'wechat-app-47ec2.appspot.com',
    iosClientId: '428089562800-u096evj856rnm8jm0eborvr3th3vo66i.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZkW1aSGEdxt4ZZqWt1MS1NIg0ZlYZ6TM',
    appId: '1:428089562800:ios:f04afb752a55092bd94d75',
    messagingSenderId: '428089562800',
    projectId: 'wechat-app-47ec2',
    storageBucket: 'wechat-app-47ec2.appspot.com',
    iosClientId: '428089562800-u096evj856rnm8jm0eborvr3th3vo66i.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechatapp',
  );
}
